name: Publish github pages

on:
  push:
    branches:
    - master
  pull_request_target: { }

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: read

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: list_pr
      run: .github/list_pr.sh
      env:
        AUTH: Bearer ${{ secrets.GITHUB_TOKEN }}
    - id: environment
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          env='{"name": "master", "url": "https://kpi-wolves.github.io/edu_db_labs/"}'
        else
          env='{"name": "pr-${{ github.event.number }}", "url": "https://kpi-wolves.github.io/edu_db_labs/${{ github.event.number }}"}'
        fi
        echo "environment=$env" > $GITHUB_OUTPUT
    outputs:
      pull_requests: ${{ steps.list_pr.outputs.pull_requests }}
      environment: ${{ steps.environment.outputs.environment }}

  build:
    runs-on: ubuntu-22.04
    needs:
    - prepare
    strategy:
      matrix:
        pull_request: ${{ fromJSON(needs.prepare.outputs.pull_requests) }}
    steps:
    - id: cache
      uses: actions/cache@v3
      with:
        path: docs/.vuepress/dist
        key: ${{ matrix.pull_request.sha }}
    - uses: actions/checkout@v3
      if: "!steps.cache.outputs.cache-hit"
    - uses: actions/setup-node@v3
      with:
        node-version: 14
      if: "!steps.cache.outputs.cache-hit"
    - run: .github/build.sh ${{ matrix.pull_request.number }} ${{ matrix.pull_request.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: "!steps.cache.outputs.cache-hit"
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.pull_request.number }}
        path: |
          docs/.vuepress/dist

  publish:
    runs-on: ubuntu-22.04
    environment: ${{ fromJSON(needs.prepare.outputs.environment) }}
    needs:
    - prepare
    - build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - run: .github/merge_artifacts.sh
    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
